version: "3.9"
services:
  app:
    build:
      context: .
      args:
        REPO_URL: https://github.com/Affan1/Rails-App
        BRANCH: main
    command: rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
